### ISSUE TITLE
找不到DataAbstract

### ISSUE THREAD

**Issue by EP012014** [KaniuBillows/NeteaseMusicAPI#1]
rt，似乎没有这个文件夹

**Comment by KaniuBillows** [comment]
你原本不应该看到这个仓库，因为我忘记将它设置为private了。但是如果你想拿到DataAbstract，它属于一个独立的.net core类库，https://github.com/KaniuBillows/MuKaiMusic在这里你可以找到它，它定义了这个音乐平台所需的数据格式
